config/routes.rb
FileMail::Application.routes.draw do
  get "admin"=> 'admin#index'
	controller :sessions do
		get 'login'=> :new
		post 'login'=>:create
		delete 'logout'=>:destroy
	end

  resources :users
	get "generator"=> "generator#index"
	get "generator/index"=> "generator#index"
	post "generator/generate"=> 'generator#generate'

	resources :divisions
  resources :outgoing_mails
  resources :incoming_mails

   root :to => 'sessions#new'

end

app/models/incoming_mail.rb
class IncomingMail < ActiveRecord::Base
	validates :code, :from, :to, :concern, :disposition, :date, :presence =>{:message => "wajib"}
	validates :code, :uniqueness => { :message => "Data sudah ada" }

	has_attached_file :attachment
	attr_protected :attachment_file_name, :attachment_content_type
end

app/controllers/incoming_mails_controller.rb
class IncomingMailsController < ApplicationController
  # GET /incoming_mails
  # GET /incoming_mails.json
  def index
    @incoming_mails = IncomingMail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incoming_mails }
    end
  end

  # GET /incoming_mails/1
  # GET /incoming_mails/1.json
  def show
    @incoming_mail = IncomingMail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @incoming_mail }
    end
  end

  # GET /incoming_mails/new
  # GET /incoming_mails/new.json
  def new
    @incoming_mail = IncomingMail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incoming_mail }
    end
  end

  # GET /incoming_mails/1/edit
  def edit
    @incoming_mail = IncomingMail.find(params[:id])
  end

  # POST /incoming_mails
  # POST /incoming_mails.json
  def create
    @incoming_mail = IncomingMail.new(params[:incoming_mail])

    respond_to do |format|
      if @incoming_mail.save
        format.html { redirect_to @incoming_mail, notice: 'Incoming mail was successfully created.' }
        format.json { render json: @incoming_mail, status: :created, location: @incoming_mail }
      else
        format.html { render action: "new" }
        format.json { render json: @incoming_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incoming_mails/1
  # PUT /incoming_mails/1.json
  def update
    @incoming_mail = IncomingMail.find(params[:id])

    respond_to do |format|
      if @incoming_mail.update_attributes(params[:incoming_mail])
        format.html { redirect_to @incoming_mail, notice: 'Incoming mail was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @incoming_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incoming_mails/1
  # DELETE /incoming_mails/1.json
  def destroy
    @incoming_mail = IncomingMail.find(params[:id])
    @incoming_mail.destroy

    respond_to do |format|
      format.html { redirect_to incoming_mails_url }
      format.json { head :ok }
    end
  end
end

app/helpers/incoming_mails_helper.rb
module IncomingMailsHelper
end

app/views/incoming_mails/_form.html.erb
<%= form_for(@incoming_mail, :html =>{ :multipart=>true}) do |f| %>
<div class="field">
<table>
	<tr>
		<td>Nomor Surat</td><td><%= f.text_field :code, :class => "text-input small-input" %></td>
	</tr>
	<tr>
		<td>Dari</td><td><%= f.text_field :from , :class => "text-input small-input" %></td>
	</tr>
	<tr>
		<td>Untuk</td><td><%= f.text_field :to , :class => "text-input small-input"%></td>
	</tr>
	<tr>
		<td>Perihal</td><td><%= f.text_field :concern , :class => "text-input small-input"%></td>
	</tr>
	<tr>
		<td>Disposisi</td><td><%= f.text_field :disposition , :class => "text-input small-input"%></td>
	</tr>
	<tr>
		<td>Tanggal</td><td><%= f.text_field :date , :class => "text-input small-input" %></td>
	</tr>
	<tr>
		<td>Keterangan</td><td><%= f.text_area :explanation, :cols=>35, :rows=>6 , :class => "wysiwyg", :style=>"width: 653px;"%></td>
	</tr>
	<tr>
		<td>File</td><td><%= f.file_field :attachment %></td>
	</tr>
	<tr>
		<td></td><td><%= f.submit "Save"  , :class => 'button'%>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Back', incoming_mails_path,:class=>'button' %></td>
	</tr>
</table>
</div>
<% end %>

app/views/incoming_mails/edit.html.erb
<h1>Editing incoming_mail</h1>

<%= render 'form' %>

<%= link_to 'Show', @incoming_mail %> |

app/views/incoming_mails/index.html.erb
<h1>Daftar Surat Masuk</h1>
<table class="table_list" border="0" cellspacing="0">
  <tr>
    <th >Nomor</th>
    <th>Nomor Surat</th>
    <th>Pengirim</th>
    <th>Tujuan</th>
    <th>Perihal</th>
    <th>Disposisi</th>
    <th>Tanggal</th>
    <th>Keterangan</th>
    <th colspan="3">Action</th>
  </tr>
<% i = 1 %>
<% @incoming_mails.each do |incoming_mail| %>
  <tr>
    <td><%= i%></td>
    <td><%= incoming_mail.code %></td>
    <td><%= incoming_mail.from %></td>
    <td><%= incoming_mail.to %></td>
    <td><%= incoming_mail.concern %></td>
    <td><%= incoming_mail.disposition %></td>
    <td><%= incoming_mail.date %></td>
    <td><%= incoming_mail.explanation %></td>
    <td><%= link_to 'Show', incoming_mail, :class => "show" %></td>
    <td><%= link_to 'Edit', edit_incoming_mail_path(incoming_mail),:class => "edit", %></td>
    <td><%= link_to 'Destroy', incoming_mail, confirm: 'Are you sure?', method: :delete,:class => "delete", %></td>
    <% i=i+1 %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incoming Mail', new_incoming_mail_path,:class=>'button' %>

app/views/incoming_mails/new.html.erb
<h1>Surat Masuk</h1>

<%= render 'form' %>

app/views/incoming_mails/show.html.erb
<h3>Detail Surat Masuk</h3>
<p id="notice"><%= notice %></p>
<table  class="table_list" border="0" cellspacing="0">
  <tr>
		<td>Nomor Surat</td><td><%= @incoming_mail.code %></td>
  </tr>
  <tr>
		<td>Pengirim</td><td><%= @incoming_mail.from %></td>
  </tr>
  <tr>
	  <td>Tujuan</td><td><%= @incoming_mail.to %></td>
	</tr>
	<tr>
		<td>Perihal</td><td><%= @incoming_mail.concern %></td>
	</tr>
	<tr>
		<td>Tanggal</td><td><%= @incoming_mail.date %></td>
	</tr>
	<tr>
		<td>Keterangan</td><td><%= @incoming_mail.explanation %></td>
	</tr>
	<tr>
		<td>Attachment</td>
		<td>
			<% if @incoming_mail.attachment? %>
			<%= link_to @incoming_mail.attachment_file_name, @incoming_mail.attachment.url %>
			<% end %>
		</td>
	</tr>

</table>
<p><%= link_to 'Edit', edit_incoming_mail_path(@incoming_mail),:class=>'button' %>  <%= link_to 'Back', incoming_mails_path,:class=>'button' %></p>