config/routes.rb
FileMail::Application.routes.draw do
  get "admin"=> 'admin#index'
	controller :sessions do
		get 'login'=> :new
		post 'login'=>:create
		delete 'logout'=>:destroy
	end

  resources :users
	get "generator"=> "generator#index"
	get "generator/index"=> "generator#index"
	post "generator/generate"=> 'generator#generate'

	resources :divisions
  resources :outgoing_mails
  resources :incoming_mails

   root :to => 'sessions#new'

end

app/models/division.rb
class Division < ActiveRecord::Base
	validates :code, :presence =>{:message => "wajib"}
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.valid?
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to divisions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<h1>Listing divisions</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @divisions.each do |division| %>
  <tr>
    <td><%= division.code %></td>
    <td><%= division.name %></td>
    <td><%= link_to 'Show', division %></td>
    <td><%= link_to 'Edit', edit_division_path(division) %></td>
    <td><%= link_to 'Destroy', division, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @division.code %>
</p>

<p>
  <b>Name:</b>
  <%= @division.name %>
</p>


<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>